"""Packet completeness scorer — deterministic, no AI.

Evaluates how complete the submission packet is against known
SBA/FEMA submission requirements. Returns a 0-100 score with
per-item breakdown.
"""

from app.models.evidence import MissingEvidence, RenameEntry
from app.models.outputs import CompletenessItem, CompletenessScore

# Required document types with weights (1=nice-to-have, 2=important, 3=critical)
_REQUIRED_ITEMS: list[tuple[str, int, list[str]]] = [
    # (item_name, weight, keywords that signal presence in rename_map)
    ("Damage photos", 3, ["damage", "photo", "exterior", "interior", "flood", "debris"]),
    ("Expense receipts", 3, ["receipt", "invoice", "expense", "payment"]),
    ("Lease or rental agreement", 2, ["lease", "rental", "agreement", "rent"]),
    ("Insurance policy or claim", 2, ["insurance", "policy", "claim"]),
    ("Bank statements", 2, ["bank", "statement", "account"]),
    ("Business license", 1, ["license", "permit", "registration", "certificate"]),
    ("Tax returns or financial statements", 1, ["tax", "return", "financial", "1040", "schedule_c"]),
    ("Utility bills", 1, ["utility", "electric", "water", "gas", "bill"]),
]

# Items that are always generated by the packet builder
_GENERATED_ITEMS: list[tuple[str, int]] = [
    ("Cover sheet", 3),
    ("Damage summary", 2),
    ("Expense ledger", 2),
    ("Evidence checklist", 1),
    ("Forbearance / waiver letters", 2),
]


def score_completeness(
    rename_map: list[RenameEntry],
    missing_evidence: list[MissingEvidence],
    has_expense_items: bool = False,
    has_damage_claims: bool = False,
    has_letters: bool = False,
) -> CompletenessScore:
    """Score the packet completeness from 0-100.

    Uses rename_map filenames + missing_evidence to determine what
    evidence the user uploaded, plus always-generated PDFs.
    """
    items: list[CompletenessItem] = []

    # Lowercase all filenames for keyword matching
    uploaded_names = [
        entry.recommended_filename.lower() for entry in rename_map
    ] + [
        entry.original_filename.lower() for entry in rename_map
    ]
    all_uploaded_text = " ".join(uploaded_names)

    missing_items_set = {m.item.lower() for m in missing_evidence}

    # 1. Check evidence-based items
    for item_name, weight, keywords in _REQUIRED_ITEMS:
        # Check if any keyword appears in uploaded filenames
        present = any(kw in all_uploaded_text for kw in keywords)

        # Also consider missing_evidence list as a negative signal
        if not present and any(item_name.lower() in mi for mi in missing_items_set):
            reason = next(
                (m.reason for m in missing_evidence if item_name.lower() in m.item.lower()),
                "Not found in uploaded evidence",
            )
        elif not present:
            reason = "Not found in uploaded evidence"
        else:
            reason = ""

        items.append(
            CompletenessItem(
                item=item_name,
                present=present,
                weight=weight,
                reason=reason,
            )
        )

    # 2. Check generated items (always present if packet is being built)
    for item_name, weight in _GENERATED_ITEMS:
        # These are generated by the packet builder — check special cases
        if item_name == "Expense ledger":
            present = has_expense_items
            reason = "" if present else "No expense items were extracted from uploads"
        elif item_name == "Damage summary":
            present = has_damage_claims
            reason = "" if present else "No damage claims were extracted from uploads"
        elif item_name == "Forbearance / waiver letters":
            present = has_letters
            reason = "" if present else "No letters generated"
        else:
            # Cover sheet and Evidence checklist are always generated
            present = True
            reason = ""

        items.append(
            CompletenessItem(
                item=item_name,
                present=present,
                weight=weight,
                reason=reason,
            )
        )

    # 3. Compute weighted score
    total_weight = sum(it.weight for it in items)
    earned_weight = sum(it.weight for it in items if it.present)
    score = round((earned_weight / total_weight) * 100) if total_weight > 0 else 0

    present_count = sum(1 for it in items if it.present)
    missing_count = sum(1 for it in items if not it.present)

    # Summary
    if score >= 90:
        summary = "Excellent — your packet is nearly complete."
    elif score >= 70:
        summary = "Good — a few more documents would strengthen your submission."
    elif score >= 50:
        summary = "Fair — several key documents are still missing."
    else:
        summary = "Incomplete — most required documents need to be uploaded."

    return CompletenessScore(
        score=score,
        items=items,
        present_count=present_count,
        missing_count=missing_count,
        summary=summary,
    )
